name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  Platform: Linux

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Running Environment"
        if: ${{ env.Platform == 'Linux' }}
        run: echo "$Platform"
    
        
