name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  Platform: macOS
jobs:
  Github-Runif-macOS:
    if: env.Platform == "macOS"
    runs-on: macos-latest
    steps:
      - run: echo macOS
  Github-Runif-windows:
    if: env.Platform == "Windows"
    runs-on: windows-latest
    steps:
      - run: echo windows
    
        
