name: macOS Builder
run-name: ${{ github.actor }} is building 
on: [release,push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: python --version
      - run: pip --version
      - run: pip install flet
      - run: flet build macos
      - uses: actions/upload-artifact@v4
        with:
          path: build/macos
          name: fletCalc-test
          retention-days: 3
